In [3]:
# Create a matrix
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2)

# Print the matrix
thismatrix

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [6]:
M <- t(thismatrix) %*% thismatrix    # producto
M

[,1] [,2]
[1,] 14   32  
[2,] 32   77

In [7]:
solve(M)   # inversa

[,1]       [,2]      
[1,]  1.4259259 -0.5925926
[2,] -0.5925926  0.2592593

### Ejercicio

In [8]:
x <- matrix(c(1,1,1,1,1,1,
              -10,0,10,-10,0,10,
             0,-5,5,0,5,-5), nrow = 6, ncol = 3)
x

[,1] [,2] [,3]
[1,] 1    -10   0  
[2,] 1      0  -5  
[3,] 1     10   5  
[4,] 1    -10   0  
[5,] 1      0   5  
[6,] 1     10  -5

In [9]:
y <- matrix(c(11,8,73,21,46,30), nrow = 6, ncol = 1)

# Bmco=(x'x)^-1 x' y

Bmco <- solve(t(x) %*% x) %*% t(x) %*% y
Bmco

[,1]  
[1,] 31.500
[2,]  1.775
[3,]  4.050

### por lm

In [12]:
X <- matrix(c( -10, 0,10,-10,0,10,
                 0,-5, 5,  0,5,-5 ), nrow = 6, ncol = 2)
modelo <- lm(y ~ X)
modelo


Call:
lm(formula = y ~ X)

Coefficients:
(Intercept)           X1           X2  
     31.500        1.775        4.050  


In [13]:
summary(modelo)


Call:
lm(formula = y ~ X)

Residuals:
    1     2     3     4     5     6 
-2.75 -3.25  3.50  7.25 -5.75  1.00 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)   
(Intercept)  31.5000     2.5495  12.355  0.00114 **
X1            1.7750     0.3122   5.685  0.01079 * 
X2            4.0500     0.6245   6.485  0.00744 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.245 on 3 degrees of freedom
Multiple R-squared:  0.9612,	Adjusted R-squared:  0.9354 
F-statistic: 37.19 on 2 and 3 DF,  p-value: 0.007635


In [14]:
sigma(modelo)

[1] 6.244998

In [20]:
anova(modelo)

Df Sum Sq Mean Sq F value Pr(>F)     
X         2  2900.5 1450.25 37.1859 0.007634979
Residuals 3   117.0   39.00      NA          NA

In [22]:
confint(modelo, level = 0.95)

2.5 %      97.5 %   
(Intercept) 23.3863221 39.613678
X1           0.7812815  2.768719
X2           2.0625629  6.037437

In [17]:
F_tabla = qf(0.95, 2, 3)
F_tabla

[1] 9.552094

In [18]:
diag(3)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [21]:
matrix(0.5, 2, 2)

[,1] [,2]
[1,] 0.5  0.5 
[2,] 0.5  0.5

In [24]:
X <- matrix(c( -10, 0,10,-10,0,10,
                 0,-5, 5,  0,5,-5 ), nrow = 6, ncol = 2)
X

[,1] [,2]
[1,] -10   0  
[2,]   0  -5  
[3,]  10   5  
[4,] -10   0  
[5,]   0   5  
[6,]  10  -5

In [26]:
vec_unos = function(n) matrix(1, nrow = n, ncol = 1)

X = cbind(vec_unos(6),X)
X

[,1] [,2] [,3]
[1,] 1    -10   0  
[2,] 1      0  -5  
[3,] 1     10   5  
[4,] 1    -10   0  
[5,] 1      0   5  
[6,] 1     10  -5